export const AudioAssets = {
    kosong: require('./voice/nol.mp3'),
    satu: require('./voice/satu.mp3'),
    dua: require('./voice/dua.mp3'),
    tiga: require('./voice/tiga.mp3'),
    empat: require('./voice/empat.mp3'),
    lima: require('./voice/lima.mp3'),
    enam: require('./voice/enam.mp3'),
    tujuh: require('./voice/tujuh.mp3'),
    delapan: require('./voice/delapan.mp3'),
    sembilan: require('./voice/sembilan.mp3'),
    antrian: require('./voice/nomor-antrian.mp3'),
    A: require('./voice/A.mp3'),
    B: require('./voice/B.mp3'),
    C: require('./voice/C.mp3'),
    D: require('./voice/D.mp3'),
    E: require('./voice/E.mp3'),
    F: require('./voice/F.mp3'),
    G: require('./voice/G.mp3'),
    H: require('./voice/H.mp3'),
    I: require('./voice/I.mp3'),
    J: require('./voice/J.mp3'),
}